server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    username: 'truongtuan'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'h68H6auu'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
